# Generated by Django 5.1.4 on 2025-01-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('medicines-pain-relief', 'Pain Relief'), ('medicines-antibiotics', 'Antibiotics'), ('medicines-supplements', 'Supplements'), ('personal-care-skin-care', 'Skin Care'), ('personal-care-hair-care', 'Hair Care'), ('personal-care-oral-care', 'Oral Care'), ('baby-care-diapers', 'Diapers'), ('baby-care-feeding', 'Feeding'), ('baby-care-toys', 'Toys'), ('lifestyle-fitness-yoga', 'Yoga'), ('lifestyle-fitness-gym', 'Gym'), ('lifestyle-fitness-supplements', 'Supplements'), ('organic-vegetables', 'Vegetables'), ('organic-fruits', 'Fruits'), ('organic-grains', 'Grains'), ('healthcare-devices-monitors', 'Monitors'), ('healthcare-devices-thermometers', 'Thermometers'), ('healthcare-devices-glucometers', 'Glucometers')], max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
